package diagnosis;

public enum Symptom {
    ANXIETY_STRESS_OR_TENSION, BEHAVIORAL_DISTURBANCES, BENT_POSTURE, BLURRED_VISION, BRADYKINESIA,
    COMMUNICATION_DIFFICULTY, CONFUSION, CONSTIPATION, DELUSIONS, DEPRESSION, DIFFICULTY_BREATHING, DIFFICULTY_LEARNING,
    DIFFICULTY_PROBLEM_SOLVING, DIFFICULTY_SWALLOWING, DIPLOPIA, EMOTIONAL_INCONTINENCE, EXCESSIVE_SALIVATION, FACIAL_MOVEMENTS, HALLUCINATIONS,
    HYPERESTHESIA, HYPERREFLEXIA, HYPOMIMIA, INABILITY_TO_COMPLETELY_MOVE, INABILITY_TO_PERFORM_ROUTINE_ACTIVITIES, INCOMPLETE_VOIDING,
    INCREASED_URINATION, INVOLVEMENT_OF_VOLUNTARY_SKELETAL_MUSCLES, IRRITABILITY, LACK_OF_ATTENTION, LACK_OF_COORDINATION, LOSS_OF_GAG_REFLEX,
    MEMORY_IMPAIRMENT, MUSCLE_CRAMPS, MUSCLE_STIFFNESS, MUSCLE_WEAKNESS, OPTIC_NEURITIS, ORIENTATION_IMPAIRMENT, PAIN_WHEN_FLEXING_UPPER_LIMB,
    PARESTHESIA, PARTIAL_OR_COMPLETE_PARALYSIS, PSYCHOSIS, PTOSIS, REDUCED_BLINKING, RESPIRATORY_COMPROMISE_DURING_CRISIS, SCANNING_SPEECH,
    SEIZURES, SLEEP_DISTURBANCE, SOCIAL_ISOLATION, SPASMS, TREMOR, UNSTEADY_GAIT, URINARY_INCONTINENCE, WEIGHT_LOSS

}
