package diagnosis;

unit PatientUnit;

rule "Confirm Alzheimer"
    when
        $patient : /patients[$symptoms : symptoms]
        $symptom : diagnosis.Symptom() from $symptoms
        $patient.getSymptoms().contains(diagnosis.Symptom("spasms"));
        $symptom.getName() != "pain when flexing upper limb" &&
        $symptom.getName() != "partial or complete paralysis" &&
        $symptom.getName() != "incomplete voiding" &&
        $symptom.getName() != "hiperesthesia" &&
        $symptom.getName() != "increased urination" &&
        $symptom.getName() != "optic neuritis" &&
        $symptom.getName() != "seizures" &&
        $symptom.getName() != "spasms" &&
        ($symptom.getName() == "memory impairment" || $symptom.getName() == "orientation impairment")

    then
        System.out.println("Alzheimer's disease is added to the list.");
        modify($patient){ addDisease(new Disease("alzheimer")) }
end

/*rule "Confirm Alzheimer"
    when
        $patient : Patient($symptoms : symptoms)
         // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms
        eval(
            Symptom(name != "pain when flexing upper limb") &&
            Symptom(name != "partial or complete paralysis") &&
            Symptom(name != "incomplete voiding") &&
            Symptom(name != "hiperesthesia") &&
            Symptom(name != "increased urination") &&
            Symptom(name != "optic neuritis") &&
            Symptom(name != "seizures") &&
            Symptom(name != "spasms") &&
            (Symptom(name == "memory impairment") ||
            Symptom(name == "orientation impairment"))
        )

    then
      //TODO ver si esto es correcto
        System.out.println("Alzheimer's disease is added to the list.");
        //insert(new Disease("alzheimer"));
        //$patient.addDisease(new Disease("alzheimer"));
        modify($patient){ addDisease(new Disease("alzheimer")) }
end

rule "Confirm ALS"
    when
        $patient : Patient($symptoms : symptoms)

        // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms
        eval(
            Symptom(name != "blurred_vision") &&
            Symptom(name != "constipation") &&
            Symptom(name != "increased urination") &&
            Symptom(name != "psicosis") &&
            Symptom(name != "optic neuritis") &&
            (Symptom(name == "muscle weakness") ||
             Symptom(name == "partial or complete paralysis") ||
             Symptom(name == "inability to completely move")
             )
        )

    then
        //TODO descartar la enfermedad de Amyotrophic
        System.out.println("Amyotrophic lateral sclerosis (ALS) is added.");
        //insert(new Disease("amyotrophicLateralSclerosis"));
        modify($patient){ addDisease(new Disease("amyotrophicLateralSclerosis")) }
end

rule "Confirm Huntington"
    when
         $patient : Patient($symptoms : symptoms)

         // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms
        eval(
            Symptom(name != "optic neuritis") &&
            Symptom(name != "ptosis") &&
            Symptom(name != "constipation") &&
            Symptom(name != "loss of gag reflex") &&
            (Symptom(name == "involvement of voluntary skeletal muscles"))
            )
    then
        //TODO descartar la enfermedad de Huntington
        System.out.println("Huntington’s disease is added.");
        //insert(new Disease("huntington"));
        modify($patient){ addDisease(new Disease("huntington")) }
end

rule "Confirm MultipleSclerosis"
    when
        $patient : Patient($symptoms : symptoms)

        // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms
         eval(
              Symptom(name != "respiratory compromise during crisis") &&
              Symptom(name != "involvement of voluntary skeletal muscles") &&
              Symptom(name != "bent posture") &&
              Symptom(name != "pain when flexing upper limb") &&
              (Symptom(name == "blurred vision")||Symptom(name == "emotional incontinence"))
              )
    then
        //TODO descartar la enfermedad de Multiple Sclerosis
        System.out.println("Multiple sclerosis is added.");
        //insert(new Disease("multipleSclerosis"));
        modify($patient){ addDisease(new Disease("multipleSclerosis")) }
end

rule "Confirm MyastheniaGravis"
    when
        $patient : Patient($symptoms : symptoms)
        // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms
        eval(
            Symptom(name != "tremor") &&
            Symptom(name != "inability to completely move") &&
            Symptom(name != "delusions") &&
            Symptom(name != "hallucinations") &&
            Symptom(name != "psicosis") &&
            (Symptom(name == "muscle weakness"))
         )
    then
        //TODO descartar la enfermedad de Myasthenia gravis
        System.out.println("Myasthenia gravis is added.");
        //insert(new Disease("myastheniaGravis"));
        modify($patient){ addDisease(new Disease("myastheniaGravis")) }
end

rule "Confirm Parkinson"
    when
        $patient : Patient($symptoms : symptoms)
        // Iterar sobre cada síntoma en la lista
        $symptom : Symptom() from $symptoms

        eval(
                    Symptom(name != "difficulty breathing") &&
                    Symptom(name != "increased urination") &&
                    Symptom(name != "optic neuritis") &&
                    Symptom(name != "seizures") &&
                    (Symptom(name == "bradykinesia") ||
                     Symptom(name == "muscle stiffness"))
                 )
    then
        //TODO descartar la enfermedad de Parkinson
        System.out.println("Parkinson’s disease is added.");
        //insert(new Disease("parkinson"));
        modify($patient){ addDisease(new Disease("parkinson")) }
end*/



