package diagnosis;

unit PatientUnit;

rule "Confirm Alzheimer"
    when

        $patient : /patients [!symptoms.contains(Symptom.PAIN_WHEN_FLEXING_UPPER_LIMB) &&
                             !symptoms.contains(Symptom.PARTIAL_OR_COMPLETE_PARALYSIS) &&
                             !symptoms.contains(Symptom.INCOMPLETE_VOIDING) &&
                             !symptoms.contains(Symptom.HYPERESTHESIA) &&
                             !symptoms.contains(Symptom.INCREASED_URINATION) &&
                             !symptoms.contains(Symptom.OPTIC_NEURITIS) &&
                             !symptoms.contains(Symptom.SEIZURES) &&
                             !symptoms.contains(Symptom.SPASMS)]

    then
        //modify($patient){ addDisease(new Disease("alzheimer")) }
        $patient.addDisease(new Disease("alzheimer"));
        System.out.println("Alzheimer's disease is added to the list.");

end

rule "Confirm ALS"
    when

        $patient : /patients [!symptoms.contains(Symptom.BLURRED_VISION) &&
                             !symptoms.contains(Symptom.CONSTIPATION) &&
                             !symptoms.contains(Symptom.INCREASED_URINATION) &&
                             !symptoms.contains(Symptom.PSYCHOSIS) &&
                             !symptoms.contains(Symptom.OPTIC_NEURITIS)
                             ]

    then
        //modify($patient){ addDisease(new Disease("amyotrophic lateral sclerosis")) }
        $patient.addDisease(new Disease("amyotrophic lateral sclerosis"));
        System.out.println("Amyotrophic Lateral Sclerosis's disease is added to the list.");

end

rule "Confirm Huntington"
    when

        $patient : /patients [!symptoms.contains(Symptom.OPTIC_NEURITIS) &&
                             !symptoms.contains(Symptom.PTOSIS) &&
                             !symptoms.contains(Symptom.CONSTIPATION) &&
                             !symptoms.contains(Symptom.LOSS_OF_GAG_REFLEX)
                             ]

    then
        //modify($patient){ addDisease(new Disease("huntington")) }
        $patient.addDisease(new Disease("huntington"));
        System.out.println("Huntington's disease is added to the list.");

end

rule "Confirm MultipleSclerosis"
    when

        $patient : /patients [!symptoms.contains(Symptom.RESPIRATORY_COMPROMISE_DURING_CRISIS) &&
                             !symptoms.contains(Symptom.INVOLVEMENT_OF_VOLUNTARY_SKELETAL_MUSCLES) &&
                             !symptoms.contains(Symptom.BENT_POSTURE) &&
                             !symptoms.contains(Symptom.PAIN_WHEN_FLEXING_UPPER_LIMB)
                             ]

    then
        //modify($patient){ addDisease(new Disease("multiple sclerosis")) }
        $patient.addDisease(new Disease("multiple sclerosis"));
        System.out.println("Multiple Sclerosis's disease is added to the list.");

end

rule "Confirm MyastheniaGravis"
    when

        $patient : /patients [!symptoms.contains(Symptom.TREMOR) &&
                             !symptoms.contains(Symptom.INABILITY_TO_COMPLETELY_MOVE) &&
                             !symptoms.contains(Symptom.DELUSIONS) &&
                             !symptoms.contains(Symptom.HALLUCINATIONS) &&
                             !symptoms.contains(Symptom.PSYCHOSIS)
                             ]

    then
        //modify($patient){ addDisease(new Disease("myasthenia gravis")) }
        $patient.addDisease(new Disease("myasthenia gravis"));
        System.out.println("Myasthenia Gravis' disease is added to the list.");

end


rule "Confirm Parkinson"
    when

        $patient : /patients [!symptoms.contains(Symptom.DIFFICULTY_BREATHING) &&
                             !symptoms.contains(Symptom.OPTIC_NEURITIS) &&
                             !symptoms.contains(Symptom.SEIZURES) &&
                             !symptoms.contains(Symptom.INCREASED_URINATION)
                             ]

    then
        //modify($patient){ addDisease(new Disease("parkinson")) }
        $patient.addDisease(new Disease("parkinson"));
        System.out.println("Parkinson's disease is added to the list.");

end



